# Generated by Django 4.1.4 on 2022-12-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='completely random notes', max_length=500)),
                ('category', models.CharField(default='life should have meaning', max_length=50)),
                ('image', models.ImageField(upload_to='photos')),
                ('place', models.CharField(default='Earth', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=10000)),
                ('highlights', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
